builds:
-
  ldflags:
    - -s -w
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - "386"
    - arm
    - arm64
    - amd64
  env:
    - CGO_ENABLED=0
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
snapshot:
  name_template: "SNAPSHOT-{{ .Commit }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^bin:'
    - '^scripts:'
    - '^fixture:'
    - Merge pull request
    - Merge branch